name: UNIFIED MODELING DRAWER - DEFAULT

on:
  push:
    branches: [main, develop]
  pull_request:
    branches:
      - main
      - develop
      - delivery

permissions: write-all

jobs:
  sonarcloud-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ${{github.workspace}}
        run: npm install

      - name: Build
        working-directory: ${{github.workspace}}
        run: npm run build

      # - name: Tests
      #   working-directory: ${{github.workspace}}
      #   run: npm test

      - name: ESlint analyze json
        working-directory: ${{github.workspace}}
        run: npm run lint:eslint:json || echo FAILED

      - name: ESlint analyze html
        working-directory: ${{github.workspace}}
        run: npm run lint:eslint || echo FAILED
        
      - name: Audit dependency
        working-directory: ${{github.workspace}}
        run: npm audit --json > ./dist/reports/audit-dependency-report.json || echo FAILED
        
      - name: Stylelint analyze
        working-directory: ${{github.workspace}}
        run: npm run lint:stylelint

      - name: Convert Audit dependency report
        working-directory: ${{github.workspace}}
        run: ./node_modules/.bin/audiso --input-file=./dist/reports/audit-dependency-report.json --output-file ./dist/reports/audit-dependency-report-sonarqube.json

      - name: Archive Analyses reports
        uses: actions/upload-artifact@v2
        with:
          name: AudiSo-Analyses-report
          path: ${{github.workspace}}/dist/reports

      # - name: Coverage reports
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Coverage-report
      #     path: ${{github.workspace}}/coverage

      - name: Setup sonarqube
        if: github.actor != 'dependabot[bot]'
        uses: warchant/setup-sonar-scanner@v3

      - name: Run SonarQube
        if: github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io/
          -Dsonar.verbose=false

      - name: SonarQube Quality Gate check
        if: github.actor != 'dependabot[bot]'
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
